# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christina Branson
email: clbranson@gmail.com
name: Christina Branson
description: > # this means to ignore newlines until "baseurl:"
  Christina Branson is a 28 year old freelance web developer based in Philadelphia, PA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://christinabranson.github.io" # the base hostname & protocol for your site
socialmedia: # url of social media accounts
   twitter: https://twitter.com/chrissybranso
   github:  https://github.com/christinabranson
   facebook: 
   linkedin: http://www.linkedin.com/in/christina-branson
   codepen: http://codepen.io/christinabranson/

# URL Settings
url: "" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title.html # permalink to put posts in "blog" subdirectory

# Blog Settings
category_dir: /blog/category/ # The subfolder to build category pages in (default is 'categories').
category_title_prefix: 'Category: ' #The string used before the category name in the page title (default is 'Category: ').
paginate: 1 # Number of posts per page
paginate_path: "/blog/page:num/"

# Environment settings
production: false
port: 8080 # local setting for cloud9 dev
host: 0.0.0.0 # local setting for cloud9 dev
timezone: "America/New_York"

# SEO settings
google_analytics_code: 123456 # code for google analytics tracking
site_logo: # used as default image when article featured image not available
facebook_app_id: # facebook app id
twitter_publisher_handle: # publisher handle for twitter meta
twitter_author_handle: # author handle for twitter meta

# Build settings
markdown: kramdown

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
    
# Gems
gems:
    - jekyll-paginate
    - jekyll-sitemap